# Generated by Django 5.1.2 on 2024-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Manta', max_length=35, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'tbl_city',
                'ordering': ['id'],
            },
        ),
    ]
