# Generated by Django 5.1.2 on 2024-11-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientesSF', '0002_clientes_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qutoe_number', models.IntegerField(blank=True, null=True, verbose_name='N°')),
                ('quote_option', models.CharField(choices=[('vida', 'Seguro de Vida'), ('auto', 'Seguro de Autos'), ('robo', 'Seguro de Robos'), ('incendio', 'Seguro contra Incendios')], max_length=25, verbose_name='Concepto')),
                ('value', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor')),
                ('diferied', models.CharField(choices=[('3_meses', '3 Meses'), ('6_meses', '6 Meses'), ('9_meses', '9 Meses'), ('12_meses', '12 Meses')], default='3_meses', max_length=10, verbose_name='Diferido')),
                ('prima', models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=10, verbose_name='Prima')),
                ('imports', models.DecimalField(decimal_places=2, default=12.5, max_digits=5, verbose_name='Impuesto (%)')),
                ('value_to_pay', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Valor a Pagar')),
                ('created_quote', models.DateTimeField(auto_now=True, verbose_name='Fecha de Cotización')),
                ('updated_quote', models.DateTimeField(auto_now_add=True, verbose_name='Última Actualización')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientesSF.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'tbl_cotizacion',
                'ordering': ['id'],
            },
        ),
    ]
