# Generated by Django 5.1.2 on 2024-11-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizadorSeguros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizador',
            name='Qutoe_number',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='created_quote',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='diferied',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='imports',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='quote_option',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='updated_quote',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='value',
        ),
        migrations.RemoveField(
            model_name='cotizador',
            name='value_to_pay',
        ),
        migrations.AddField(
            model_name='cotizador',
            name='derecho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Derecho'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA (15%)'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='plazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo (días)'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='prima_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prima Mínima'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='super_banco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Super Banco (3,5%)'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa (%)'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='tipo_poliza',
            field=models.CharField(blank=True, choices=[('BUEN_USO', 'Buen uso del anticipo'), ('CUMPLIMIENTO', 'Cumplimiento de contrato'), ('FIDELIDAD', 'Fidelidad'), ('RESPONSABILIDAD', 'Responsabilidad civil')], max_length=50, null=True, verbose_name='Tipo de Póliza'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='valor_asegurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Asegurado'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia'),
        ),
        migrations.AlterField(
            model_name='cotizador',
            name='prima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prima'),
        ),
    ]
