# Generated by Django 5.1.2 on 2024-11-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0001_initial'),
        ('ClientesSF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ciudad.ciudad', verbose_name='Ciudad'),
        ),
    ]
