# Generated by Django 5.1.2 on 2024-11-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientesSF', '0002_clientes_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cotizacion', models.CharField(max_length=35, verbose_name='cotizacion')),
                ('quote_option', models.CharField(choices=[('vida', 'seguro de vida'), ('auto', 'Seguro de Autos'), ('robo', 'Seguro de Robos'), ('incendio', 'seguro contra incendios')], max_length=25, verbose_name='Producto')),
                ('created_quote', models.DateTimeField(auto_now=True, verbose_name='fecha de Cotizacion')),
                ('updated_quote', models.DateTimeField(auto_now_add=True, verbose_name='fecha de la ultima Cotizacion')),
                ('quote_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Base')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientesSF.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'tbl_cotizacion',
                'ordering': ['id'],
            },
        ),
    ]
