# Generated by Django 5.1.2 on 2024-11-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='name_cotizacion',
        ),
    ]
